language: cpp
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base qt59quickcontrols qt59quickcontrols2 qt59declarative qt59tools
  - source /opt/qt*/bin/qt*-env.sh

script:
  - bash build.sh
  - bash create-linux-appdir.sh
  - find .
  - find ..

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
