language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-5 CXX=g++-5
    - compiler: clang
      env: COMPILER=clang++-3.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - sourceline: 'ppa:beineri/opt-qt58-trusty'
      - sourceline: 'deb http://cz.archive.ubuntu.com/ubuntu xenial main universe'
    packages:
      - clang-3.8
      - g++-5
      - extra-cmake-modules
      - qt58base
      - qt58graphicaleffects
      - qt58quickcontrols2
      - qt58svg
      - qt58declarative

before_install:
  - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
  - source $QT_ENV_SCRIPT

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
  # build binaries and generate appimage
  - mkdir -p ./appdir
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=../appdir/usr/. ..
  - make -j4
  - sudo make INSTALL_ROOT=../appdir install ; sudo chown -R $USER ../appdir ; find ../appdir/
  - cd ../
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=. -verbose=2
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -qmldir=. -verbose=2
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - chmod a+x ElectronPass-x86_64.AppImage

  # upload image to transfer.sh
  - curl --upload-file ./ElectronPass*.AppImage https://transfer.sh/electronpass-git.$(git rev-parse --short HEAD)-x86_64.AppImage
