language: cpp
sudo: required
dist: trusty

matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: COMPILER=g++-5 CXX=g++-5
    - compiler: clang
      env: COMPILER=clang++-3.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - sourceline: 'ppa:beineri/opt-qt571-trusty'
      - sourceline: 'deb http://cz.archive.ubuntu.com/ubuntu xenial main universe'
    packages:
      - clang-3.8
      - g++-5
      - extra-cmake-modules
      - checkinstall
      - qt57base
      - qt57graphicaleffects
      - qt57quickcontrols2
      - qt57svg
      - qt57declarative
      - qt57wayland
before_install:
  - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
  - source $QT_ENV_SCRIPT

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
  # Install a recent CMake
  - CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
  - mkdir cmake
  - wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  - cmake --version

  # build and install project
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - make
  - sudo make install

  # generate appimage
  - sudo checkinstall --pkgname=app --pkgversion="1" --pkgrelease="1" --backup=no --fstrans=no --default --deldoc
  - mkdir appdir ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; find .
  - cp ./usr/share/applications/electronpass.desktop .
  - cp ./usr/share/icons/hicolor/scalable/apps/electronpass.svg .
  - cd ..
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/electronpass -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/electronpass -appimage
  - curl --upload-file ./ElectronPass*.AppImage https://transfer.sh/electronpass-git.$(git rev-parse --short HEAD)-x86_64.AppImage
