language: cpp
sudo: required
services:
  - docker

before_install:
  - cd .builder/
  - docker build -t builder .

script:
  - docker run --name builder -e TRAVIS_REPO_SLUG=electronpass/electronpass-desktop -e GITHUB_TOKEN=${GITHUB_TOKEN} -e keys_encryption_password=${keys_encryption_password} -i -t builder

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
