language: ruby
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      rvm: 1.9.3
      env: COMPILER=g++-5 CXX=g++-5
    - compiler: clang
      rvm: 1.9.3
      env: COMPILER=clang++-3.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - sourceline: 'ppa:beineri/opt-qt58-trusty'
      - sourceline: 'deb http://cz.archive.ubuntu.com/ubuntu xenial main universe'
      # For libelectronpass
      - sourceline: 'ppa:chris-lea/libsodium'
      - sourceline: 'deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
      - sourceline: 'deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
      - sourceline: 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main'
        key_url: 'http://llvm.org/apt/llvm-snapshot.gpg.key'

    packages:
      - clang-3.8
      - g++-5
      - extra-cmake-modules
      - qt58base
      - qt58graphicaleffects
      - qt58quickcontrols2
      - qt58svg
      - qt58declarative
      - libsodium-dev
      - curl

before_install:
  - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
  - source $QT_ENV_SCRIPT
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
  # install a recent CMake
  - CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
  - mkdir cmake
  - wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  - cmake --version

  # clone and install libelectronpass
  - git clone https://github.com/electronpass/libelectronpass.git
  - cd libelectronpass
  - cmake .
  - sudo make install
  - sudo ldconfig /usr/local/lib
  - cd ..

  # build binaries and generate appimage
  - mkdir -p ./appdir
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=../appdir/usr/. ..
  - make -j4
  - sudo make INSTALL_ROOT=../appdir install ; sudo chown -R $USER ../appdir ; find ../appdir/
  - cd ../
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - sudo ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=.
  - sudo ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -qmldir=.
  - find ./appdir -executable -type f -exec ldd {} \; | grep " =!> /usr" | cut -d " " -f 2-3 | sort | uniq
  - chmod a+x ElectronPass-x86_64.AppImage

  # install gem for fpm and configure fpm variables
  - sudo gem install --no-ri --no-rdoc fpm
  - LOWERAPP=appdir
  - VERSION=0.0.1
  - DIR=appdir

  # build deb with fpm
  - fpm -s dir -t deb -n $LOWERAPP -v $VERSION -C $DIR

  # upload images to transfer.sh
  - curl --upload-file ./ElectronPass*.AppImage https://transfer.sh/electronpass-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - curl --upload-file ./*.deb https://transfer.sh/electronpass-git.$(git rev-parse --short HEAD)-x86_64.deb
  - curl --upload-file ./*.rpm https://transfer.sh/electronpass-git.$(git rev-parse --short HEAD)-x86_64.rpm
