language: cpp
sudo: required
services:
  - docker

before_install:
  - sudo apt-get install -y fuse
  - sudo modprobe fuse
  - user="$(whoami)"
  - sudo usermod -a -G fuse $user
  - cd .builder/
  - docker build -t builder .

script:
  - docker run --name builder -e TRAVIS_REPO_SLUG=electronpass/electronpass-desktop -e GITHUB_TOKEN=${GITHUB_TOKEN} -e keys_encryption_password=${keys_encryption_password} -it --cap-add SYS_ADMIN --device /dev/fuse builder

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
